### PR TITLE
Fix unsafe string serialisation on specific systems (CentOS 6)

### PR DESCRIPTION
**Pull request by Alkalinee**
fix issue #54

### CODE REVIEW

**Comment by tomba** [comment]
Please fix your indentation. It is impossible to review the patch if you change the indentation.

**Comment by Alkalinee** [comment]
I didnt change the indentation, the second commit fixes a logic problem I had in the first one (when the string only has null values). The first commit is described in the referenced issue. Sure, that fixes a bug which has technically nothing to do with the NetSerializer, but just because I noticed it on CentOS 6 doesn't mean that CentOS 6 is the only system where it occures. You don't have to merge that, but it's nice for people who face the same bug. You have to choose if you want a bug free library or a "technical" bug free library. If you don't merge it, you can maybe notice is somewhere (FAQ?) so people who are writing server applications like I do can easily find it and apply the changes.

**Comment by tomba** [comment]
See the diff of the first commit. You changed the indentation, and so git shows the whole method as changed, even if you only changed parts of it.

I don't have problem with applying patches to deal with issues on some specific widely used platforms. But that's the last resort. The first step is to figure out what the bug is. Then try to fix the bug. And if, for whatever reason, fixing the bug fails, only then write a workaround.

**Comment by tomba** [comment]
Also, if you write a patch to fix something, but make a mistake in that patch, and thus write another patch to fix the first one, don't send those two forward. Squash them together and just send the fixed patch.

**Comment by Alkalinee** [comment]
> The first step is to figure out what the bug is.

The bug is that the unsafe Encoder.Convert() method does nothing (it doesn't change the array in any way, it doesn't even fill it with zeros, it just leaves the array like it is). 

> but make a mistake in that patch, and thus write another patch to fix the first one

Why should I delete all commits just to commit that again? Whats the problem with 3 instead of 1 commit? All changes are anyway merged here (in `Files changed`).

**Comment by tomba** [comment]
> The bug is that the unsafe Encoder.Convert() method does nothing (it doesn't change the array in any way, it doesn't even fill it with zeros, it just leaves the array like it is). 

Where is the bug? Is it in Mono's libraries? System's libraries? Bad Mono internationalization configuration? We have no idea.

I won't merge workarounds for issues that are as unclear as this.

> Why should I delete all commits just to commit that again? Whats the problem with 3 instead of 1 commit? All changes are anyway merged here (in Files changed).

Why wouldn't you? Why do you want to show the reviewers that you made a mistake, and then fixed it? How is that related to the actual issue? That is just wasting the reviewer's time, and makes the git history messier.

And your patches are still unreviewable: you just created a third patch that changes the indentation back to tabs. But there is still no way for me to see the change that you actually made. All I see is a big patch changing all indentation, and somewhere in the middle there's probably the actual change.

When you send a pull request, _never_ send fixes to your patches in that same pull request. Squash the fixes, so that the reviewer only sees to final cleaned up version.

**Comment by Alkalinee** [comment]
> Where is the bug? Is it in Mono's libraries? System's libraries? Bad Mono internationalization configuration? We have no idea.

We don't know and I don't have the time to look through the Mono source just to tell you where the bug really is. The bug didn't only come up on my VPS but also on the VPS of at least 4 users of my program.

> And your patches are still unreviewable

https://github.com/tomba/netserializer/pull/55/files shows you the changes of all commits - it looks exactly the same like if it was just one commit. You don't have to look though all commits, it summarizes all changes for you.

**Comment by tomba** [comment]
> We don't know and I don't have the time to look through the Mono source just to tell you where the bug really is. The bug didn't only come up on my VPS but also on the VPS of at least 4 users of my program.

That's ok, you can have the workaround in your version for the time being. I can't apply patches that implement workarounds for vague bugs in external components.

And I'm not dismissing the bug report. It may well be that my unsafe code there is broken, and for some reason it only affects some platforms. But if that's the case, your workaround would only hide the bug.

Also, there already is the safe version for string serialization. Why didn't you use that?

> https://github.com/tomba/netserializer/pull/55/files shows you the changes of all commits

Right. And if, say, a few weeks from now, I notice that NetSerializer is not working, and start looking at the changes in the history, your suggestion is that I need to figure out which bunch of commits belong together,  then compose a diff of those commits, only to see what they really change?

I don't understand why you are arguing about this. Your commits are just sloppy, and squashing them together with git takes about 5 seconds. Any serious project would reject such commits right away.

**Comment by Alkalinee** [comment]
> Also, there already is the safe version for string serialization. Why didn't you use that?

That was the first thing I tried and that worked well, but it is not compatible to the unsafe method and I would rather say that CentOS 6 isnt supported than causing a huge incompatibility.

> Your commits are just sloppy, and squashing them together with git takes about 5 seconds

The first commit is the root commit (because it's a new branch) so I can't just delete it, I'm not using git quite often. Anyways, if you want to merge it, I will merge the commits into one commit.

**Comment by tomba** [comment]
> That was the first thing I tried and that worked well, but it is not compatible to the unsafe method

Ok, well _that_ is a clear bug that needs to be fixed.

> The first commit is the root commit (because it's a new branch) so I can't just delete it, I'm not using git quite often. Anyways, if you want to merge it, I will merge the commits into one commit.

Sure you can.

If you're in the branch, containing the three commits, you can just do:

```
git reset HEAD^^^
git commit -a
```

And then push it to github with -f flag

```
git push -f origin
```

**Comment by Alkalinee** [comment]
> Sure you can.

Thank you :)

Btw one question: Why isn't there a generic deserialize function? Is there a reason or did just nobody add it?

**Comment by tomba** [comment]
I created Issue #56 for the safe/unsafe string serialization problem.

**Comment by tomba** [comment]
> Why isn't there a generic deserialize function? Is there a reason or did just nobody add it?

Well, I have thought about it. But I think usually there should be a benefit when using generics. In this case, all the generic function would do (and hide) is the type cast. There's isn't much difference from caller's perspective:

```
var ob = (Foo)ns.Deserialize(stream);
var ob = ns.Deserialize<Foo>(stream);
```

The small downside with the generic version is that it hides the typecast, and so if you are deserializing a struct, it will do unboxing without you knowing about it. Maybe you would do the unboxing anyway (with typecast), but maybe you wouldn't.

Also, there are the SerializeDirect() and DeserializeDirect() generic methods that do benefit from the generics.

**Comment by tomba** [comment]
I added a "Known issues" section to NetSerializer documentation, and listed the CentOS 6 issue there.

**Comment by Alkalinee** [comment]
That's nice, thank you

**Pull request closed without merging**
