### PR TITLE
Version Serializer

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by tomba** [comment]
A few generic comments:

- Provide information what the changes do and why are they needed (when it's not trivially obvious).
- Never send fixes to your patches in the same pull request. Fix and clean up your commits before sending the pull request.
- I will never merge commits that change indentation or such, as the "Forgot to commit csproj" does.

**Comment by jogibear9988** [comment]
Is it ok so?

**Comment by tomba** [comment]
No, you change the whole NetSerializer.csproj file. If you add a new file, I expect a single line added to the .csproj file.

And the important question is still unclear: why is this needed at all? class Version is serializable, so it should just work with the generic serializer.

**Comment by jogibear9988** [comment]
I thought I got the error Version was not Serializable... Maybe I was wrong, I'll test once more

**Comment by tomba** [comment]
I'm closing this as afaik there's no need for a serializer for Verson. Re-open if needed.

**Pull request closed without merging**
