### PR TITLE
Updated to .NET Standard 2.0

### PR DESCRIPTION
**Pull request by shaunsales**

### CODE REVIEW

**Comment by tomba** [comment]
There's no description for the pull request, so I'm not sure what's the purpose here. But this seems to break compilation, removes code without explanation, and does a lot of unrelated changes in single commits.

**Comment by shaunsales** [comment]
Sorry, not sure how there is no description, I thought I left one.

Could you let me know what is broken in the compiler? I ran all relevant tests and am using this in my project without any issues.

**Comment by tomba** [comment]
I didn't look closely, just did a quick test. I think you're removing support for .Net framework:

`tomba@lappyti:~/work-lappy/netserializer (master)$ nuget restore
MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
/usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error : The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [/home/tomba/work-lappy/netserializer/Test/Test.csproj]
/usr/lib/mono/msbuild/15.0/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5): error : The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [/home/tomba/work-lappy/netserializer/PrimitiveTest/PrimitiveTest.csproj]
`

Which brings back the question about the intent. The point here is to remove support for old framework and only target .Net Core 2.2? That's not ok.

I have to admit I haven't been following .Net for a few years now, so correct me if I'm wrong, but afaik .Net Framework is still needed. .Net Core is a totally different environment.

**Comment by shaunsales** [comment]
Newer packages should target .NET Standard 2.0, which will run under both .NET Framework and .NET Core. And you're right, I had the Test projects targeting .NET Core 2.2 (the main NetSerializer lib was netstandard2.0), which I've changed this to .NET Standard 2.0. Thanks for the note.

The code I removed appeared to be an unused codepath for generating a debugging assembly. It was not compatible with .NET Standard 2.0, so I removed it. Maybe it would make sense to reimplement it, but I wasn't sure how it was intended to be used.

Lastly, `DynamicMethod.DefineParameter` is not exposed in .NET Standard 2.0, and isn't critical path for NetSerializer to function, so I commented it for now with a note to re-expose it when .NET Core 3.0 is released - support for the latter call is tagged for release then.

Hope this helps to make sense of the changes.

**Comment by tomba** [comment]
Ok, now this builds on Ubuntu, but the test executables are built as dlls...

The debugging assembly has been very useful. With dynamic methods (at least previously) it was more or less impossible to see the final IL code, so if things didn't work, it was very difficult to debug. So, I generated a normal .dll (which couldn't be used at runtime due to access restrictions), which I could then study and see the exact IL generated.

**Comment by tomba** [comment]
I did some reading, and I confused .Net Standard to .Net Core. Yes, it makes sense to update to .Net Standard.

Did you check if .Net Standard 2 has something that is required by NetSerializer, which .Net Standard 1 does not have?

**Comment by shaunsales** [comment]
By default `dotnet build` produces portable assemblies that can be executed using `dotnet run`. To output platform specific executables, you can use `dotnet publish -c Debug -r win10-x64` for example.

I believe we could target the .NET Standard 1.0 - I don't believe NetSerializer has any dependencies on .NET Standard 2.0, but I'll need to check. I didn't target 1.0 since pretty much all packages are targeting 2.0 now, but it may be useful to those running older .NET projects.

In regards to generating IL from the dynamic methods I believe this should be supported, but need to do a bit of research to look into the best way to do it.

**Comment by tomba** [comment]
Isn't "dotnet" command a .Net Core component? I'm running Ubuntu + Mono, and build with msbuild. I don't have "dotnet". Targeting .Net Standard removes the ability to build exes?

I see that I can run the dll just with "mono Test.exe", so this is probably not an issue. Just confusing...

**Comment by shaunsales** [comment]
Yes, it's still a bit confusing. I think the .NET team plans to bring all of this together in .NET 5.0, which will merge Framework, Core and Mono/Xamarin. Fingers crossed!

**Comment by tomba** [comment]
@shaunsales Can you check #71 and comment if it works for you?

**Pull request closed without merging**
